from __future__ import annotations

import re
from pathlib import Path

from breakbot.config import BreakBotConfig
from breakbot.models import Finding, GeneratedTest, SourceBundle


class AdversarialTestGenerator:
    def __init__(self, config: BreakBotConfig):
        self.config = config

    def generate(self, source: SourceBundle, findings: list[Finding]) -> list[GeneratedTest]:
        tests: list[GeneratedTest] = []
        for index, finding in enumerate(findings[: self.config.max_generated_tests], start=1):
            module_name = _module_name(finding.file_path)
            test_name = f"test_breakbot_{index}_{_slug(finding.title)}"
            content = self._render_test(test_name, module_name, finding)
            tests.append(
                GeneratedTest(
                    name=test_name,
                    file_path=f"tests/{test_name}.py",
                    content=content,
                    targets=[finding.file_path],
                )
            )
        return tests

    def _render_test(self, test_name: str, module_name: str, finding: Finding) -> str:
        payloads = ["None", "''", "[]", "{}", "0", "'../../etc/passwd'", "'${{7*7}}'"]
        payload_lines = "\n".join(f"        {payload}," for payload in payloads)
        return f'''"""Generated by BreakBot for: {finding.title}."""

import importlib
import inspect


def test_{test_name}():
    module = importlib.import_module("{module_name}")
    public_functions = [
        value for name, value in vars(module).items()
        if callable(value) and not name.startswith("_")
    ]
    assert public_functions, "BreakBot expected at least one public callable to attack"

    payloads = [
{payload_lines}
    ]
        crashes = []
    for func in public_functions:
        signature = inspect.signature(func)
        positional_count = sum(
            1 for parameter in signature.parameters.values()
            if parameter.default is inspect._empty
            and parameter.kind in (
                parameter.POSITIONAL_ONLY,
                parameter.POSITIONAL_OR_KEYWORD,
            )
        )
        args = payloads[:max(positional_count, 1)]
        try:
            func(*args)
        except Exception as exc:
            crashes.append((func.__name__, type(exc).__name__, str(exc)))

    assert not crashes, f"Adversarial payloads exposed unhandled exceptions: {{crashes}}"
'''


def _module_name(file_path: str) -> str:
    path = Path(file_path)
    without_suffix = path.with_suffix("")
    parts = [part for part in without_suffix.parts if part not in {".", ""}]
    if parts and parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts) or "pasted_code"


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.lower()).strip("_")
    return slug[:40] or "case"
